// Copyright (c) CurioSwitch (choko@curioswitch.org)
// SPDX-License-Identifier: BUSL-1.1

// Package planexec contains the structured input and output used when an AI
// groups recipe steps into an execution plan.
package planexec

import (
	"fmt"

	"google.golang.org/genai"

	"github.com/curioswitch/cookchat/common/cookchatdb"
)

// RecipeInput identifies a recipe and provides the content whose zero-based
// step indexes can be referenced by the generated execution plan.
type RecipeInput struct {
	RecipeID string                   `json:"recipeId"`
	Content  cookchatdb.RecipeContent `json:"content"`
}

// StepReference points to one original recipe step without allowing the AI to
// rewrite its description or image URL.
type StepReference struct {
	RecipeID  string `json:"recipeId"`
	StepIndex int    `json:"stepIndex"`
}

// GeneratedStepGroup is a group returned by the AI before its step references
// are resolved back to stored recipe data.
type GeneratedStepGroup struct {
	Label string          `json:"label"`
	Steps []StepReference `json:"steps"`
	Note  string          `json:"note"`
}

// GeneratedPlan is the part of a plan generated by the AI.
type GeneratedPlan struct {
	StepGroups []GeneratedStepGroup `json:"stepGroups"`
	Notes      []string             `json:"notes"`
}

// ResponseSchema returns the schema for an AI-generated execution plan.
func ResponseSchema() *genai.Schema {
	return &genai.Schema{
		Type:        "object",
		Description: "The grouped steps for preparing a meal.",
		Properties: map[string]*genai.Schema{
			"stepGroups": {
				Type:        "array",
				Description: "Groups of recipe step references to execute together.",
				Items: &genai.Schema{
					Type: "object",
					Properties: map[string]*genai.Schema{
						"label": {
							Type:        "string",
							Description: "The label of the step group, e.g. 準備, 調理, 仕上げ.",
						},
						"steps": {
							Type:        "array",
							Description: "References to original recipe steps.",
							Items: &genai.Schema{
								Type: "object",
								Properties: map[string]*genai.Schema{
									"recipeId": {
										Type:        "string",
										Description: "The recipeId from the input recipe.",
									},
									"stepIndex": {
										Type:        "integer",
										Description: "The zero-based index in the input recipe's content.steps array.",
									},
								},
								Required: []string{"recipeId", "stepIndex"},
							},
						},
						"note": {
							Type:        "string",
							Description: "A useful note for executing the steps in this group.",
						},
					},
					Required: []string{"label", "steps"},
				},
			},
			"notes": {
				Type:        "array",
				Description: "Useful notes for preparing the entire meal.",
				Items: &genai.Schema{
					Type: "string",
				},
			},
		},
		Required: []string{"stepGroups"},
	}
}

// ResolveStepGroups replaces generated step references with the description
// and image URL stored on the referenced recipe step.
func ResolveStepGroups(groups []GeneratedStepGroup, recipes []cookchatdb.Recipe) ([]cookchatdb.StepGroup, error) {
	recipesByID := make(map[string]cookchatdb.Recipe, len(recipes))
	for _, recipe := range recipes {
		recipesByID[recipe.ID] = recipe
	}

	type stepKey struct {
		recipeID string
		index    int
	}
	seen := make(map[stepKey]struct{})
	resolved := make([]cookchatdb.StepGroup, len(groups))
	for groupIndex, group := range groups {
		steps := make([]cookchatdb.RecipeStep, len(group.Steps))
		for stepIndex, reference := range group.Steps {
			recipe, ok := recipesByID[reference.RecipeID]
			if !ok {
				return nil, fmt.Errorf("planexec: recipe %q not found", reference.RecipeID)
			}
			if reference.StepIndex < 0 || reference.StepIndex >= len(recipe.Content.Steps) {
				return nil, fmt.Errorf("planexec: step index %d is out of range for recipe %q", reference.StepIndex, reference.RecipeID)
			}

			key := stepKey{recipeID: reference.RecipeID, index: reference.StepIndex}
			if _, ok := seen[key]; ok {
				return nil, fmt.Errorf("planexec: recipe %q step %d is referenced more than once", reference.RecipeID, reference.StepIndex)
			}
			seen[key] = struct{}{}

			source := recipe.Content.Steps[reference.StepIndex]
			imageURL := source.ImageURL
			if reference.StepIndex < len(recipe.StepImageURLs) && recipe.StepImageURLs[reference.StepIndex] != "" {
				imageURL = recipe.StepImageURLs[reference.StepIndex]
			}
			steps[stepIndex] = cookchatdb.RecipeStep{
				Description: source.Description,
				ImageURL:    imageURL,
			}
		}
		resolved[groupIndex] = cookchatdb.StepGroup{
			Label: group.Label,
			Steps: steps,
			Note:  group.Note,
		}
	}
	return resolved, nil
}
