// @generated by protoc-gen-connect-query v2.0.1 with parameter "target=ts"
// @generated from file frontendapi/frontend.proto (package frontendapi, syntax proto3)
/* eslint-disable */

import { FrontendService } from "./frontend_pb";

/**
 * Get the recipe for a given recipe ID.
 *
 * @generated from rpc frontendapi.FrontendService.GetRecipe
 */
export const getRecipe = FrontendService.method.getRecipe;

/**
 * Get the list of recipes.
 *
 * @generated from rpc frontendapi.FrontendService.ListRecipes
 */
export const listRecipes = FrontendService.method.listRecipes;

/**
 * Start a chat session.
 *
 * @generated from rpc frontendapi.FrontendService.StartChat
 */
export const startChat = FrontendService.method.startChat;

/**
 * Add a new recipe.
 *
 * @generated from rpc frontendapi.FrontendService.AddRecipe
 */
export const addRecipe = FrontendService.method.addRecipe;

/**
 * Generate a recipe based on a prompt.
 *
 * @generated from rpc frontendapi.FrontendService.GenerateRecipe
 */
export const generateRecipe = FrontendService.method.generateRecipe;

/**
 * Generate a scheduled recipe plan.
 *
 * @generated from rpc frontendapi.FrontendService.GeneratePlan
 */
export const generatePlan = FrontendService.method.generatePlan;
