// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file frontendapi/frontend.proto (package frontendapi, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file frontendapi/frontend.proto.
 */
export const file_frontendapi_frontend: GenFile = /*@__PURE__*/
  fileDesc("Chpmcm9udGVuZGFwaS9mcm9udGVuZC5wcm90bxILZnJvbnRlbmRhcGkiPAoLQ2hhdENvbnRlbnQSEQoHbWVzc2FnZRgBIAEoCUgAEg8KBWF1ZGlvGAIgASgMSABCCQoHcGF5bG9hZCI4CgtDaGF0UmVxdWVzdBIpCgdjb250ZW50GAEgASgLMhguZnJvbnRlbmRhcGkuQ2hhdENvbnRlbnQiOQoMQ2hhdFJlc3BvbnNlEikKB2NvbnRlbnQYASABKAsyGC5mcm9udGVuZGFwaS5DaGF0Q29udGVudDJOCgtDaGF0U2VydmljZRI/CgRDaGF0EhguZnJvbnRlbmRhcGkuQ2hhdFJlcXVlc3QaGS5mcm9udGVuZGFwaS5DaGF0UmVzcG9uc2UoATABQj1aO2dpdGh1Yi5jb20vY3VyaW9zd2l0Y2gvY29va2NoYXQvZnJvbnRlbmQvYXBpL2dvO2Zyb250ZW5kYXBpYgZwcm90bzM");

/**
 * The content of a chat message.
 *
 * @generated from message frontendapi.ChatContent
 */
export type ChatContent = Message<"frontendapi.ChatContent"> & {
  /**
   * @generated from oneof frontendapi.ChatContent.payload
   */
  payload: {
    /**
     * A text message.
     *
     * @generated from field: string message = 1;
     */
    value: string;
    case: "message";
  } | {
    /**
     * An audio message.
     *
     * @generated from field: bytes audio = 2;
     */
    value: Uint8Array;
    case: "audio";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message frontendapi.ChatContent.
 * Use `create(ChatContentSchema)` to create a new message.
 */
export const ChatContentSchema: GenMessage<ChatContent> = /*@__PURE__*/
  messageDesc(file_frontendapi_frontend, 0);

/**
 * A request to send in a chat.
 *
 * @generated from message frontendapi.ChatRequest
 */
export type ChatRequest = Message<"frontendapi.ChatRequest"> & {
  /**
   * The content of the chat message.
   *
   * @generated from field: frontendapi.ChatContent content = 1;
   */
  content?: ChatContent;
};

/**
 * Describes the message frontendapi.ChatRequest.
 * Use `create(ChatRequestSchema)` to create a new message.
 */
export const ChatRequestSchema: GenMessage<ChatRequest> = /*@__PURE__*/
  messageDesc(file_frontendapi_frontend, 1);

/**
 * A response in a chat.
 *
 * @generated from message frontendapi.ChatResponse
 */
export type ChatResponse = Message<"frontendapi.ChatResponse"> & {
  /**
   * The content of the chat message.
   *
   * @generated from field: frontendapi.ChatContent content = 1;
   */
  content?: ChatContent;
};

/**
 * Describes the message frontendapi.ChatResponse.
 * Use `create(ChatResponseSchema)` to create a new message.
 */
export const ChatResponseSchema: GenMessage<ChatResponse> = /*@__PURE__*/
  messageDesc(file_frontendapi_frontend, 2);

/**
 * A chat service.
 *
 * @generated from service frontendapi.ChatService
 */
export const ChatService: GenService<{
  /**
   * Chat with a stream of messages.
   *
   * @generated from rpc frontendapi.ChatService.Chat
   */
  chat: {
    methodKind: "bidi_streaming";
    input: typeof ChatRequestSchema;
    output: typeof ChatResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_frontendapi_frontend, 0);

