// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: frontendapi/frontend.proto

package frontendapiconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	_go "github.com/curioswitch/cookchat/frontend/api/go"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ChatServiceName is the fully-qualified name of the ChatService service.
	ChatServiceName = "frontendapi.ChatService"
	// FrontendServiceName is the fully-qualified name of the FrontendService service.
	FrontendServiceName = "frontendapi.FrontendService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ChatServiceChatProcedure is the fully-qualified name of the ChatService's Chat RPC.
	ChatServiceChatProcedure = "/frontendapi.ChatService/Chat"
	// FrontendServiceGetRecipeProcedure is the fully-qualified name of the FrontendService's GetRecipe
	// RPC.
	FrontendServiceGetRecipeProcedure = "/frontendapi.FrontendService/GetRecipe"
	// FrontendServiceListRecipesProcedure is the fully-qualified name of the FrontendService's
	// ListRecipes RPC.
	FrontendServiceListRecipesProcedure = "/frontendapi.FrontendService/ListRecipes"
	// FrontendServiceStartChatProcedure is the fully-qualified name of the FrontendService's StartChat
	// RPC.
	FrontendServiceStartChatProcedure = "/frontendapi.FrontendService/StartChat"
	// FrontendServiceAddRecipeProcedure is the fully-qualified name of the FrontendService's AddRecipe
	// RPC.
	FrontendServiceAddRecipeProcedure = "/frontendapi.FrontendService/AddRecipe"
)

// ChatServiceClient is a client for the frontendapi.ChatService service.
type ChatServiceClient interface {
	// Chat with a stream of messages.
	Chat(context.Context) *connect.BidiStreamForClient[_go.ChatRequest, _go.ChatResponse]
}

// NewChatServiceClient constructs a client for the frontendapi.ChatService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewChatServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ChatServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	chatServiceMethods := _go.File_frontendapi_frontend_proto.Services().ByName("ChatService").Methods()
	return &chatServiceClient{
		chat: connect.NewClient[_go.ChatRequest, _go.ChatResponse](
			httpClient,
			baseURL+ChatServiceChatProcedure,
			connect.WithSchema(chatServiceMethods.ByName("Chat")),
			connect.WithClientOptions(opts...),
		),
	}
}

// chatServiceClient implements ChatServiceClient.
type chatServiceClient struct {
	chat *connect.Client[_go.ChatRequest, _go.ChatResponse]
}

// Chat calls frontendapi.ChatService.Chat.
func (c *chatServiceClient) Chat(ctx context.Context) *connect.BidiStreamForClient[_go.ChatRequest, _go.ChatResponse] {
	return c.chat.CallBidiStream(ctx)
}

// ChatServiceHandler is an implementation of the frontendapi.ChatService service.
type ChatServiceHandler interface {
	// Chat with a stream of messages.
	Chat(context.Context, *connect.BidiStream[_go.ChatRequest, _go.ChatResponse]) error
}

// NewChatServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewChatServiceHandler(svc ChatServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	chatServiceMethods := _go.File_frontendapi_frontend_proto.Services().ByName("ChatService").Methods()
	chatServiceChatHandler := connect.NewBidiStreamHandler(
		ChatServiceChatProcedure,
		svc.Chat,
		connect.WithSchema(chatServiceMethods.ByName("Chat")),
		connect.WithHandlerOptions(opts...),
	)
	return "/frontendapi.ChatService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ChatServiceChatProcedure:
			chatServiceChatHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedChatServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedChatServiceHandler struct{}

func (UnimplementedChatServiceHandler) Chat(context.Context, *connect.BidiStream[_go.ChatRequest, _go.ChatResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("frontendapi.ChatService.Chat is not implemented"))
}

// FrontendServiceClient is a client for the frontendapi.FrontendService service.
type FrontendServiceClient interface {
	// Get the recipe for a given recipe ID.
	GetRecipe(context.Context, *connect.Request[_go.GetRecipeRequest]) (*connect.Response[_go.GetRecipeResponse], error)
	// Get the list of recipes.
	ListRecipes(context.Context, *connect.Request[_go.ListRecipesRequest]) (*connect.Response[_go.ListRecipesResponse], error)
	// Start a chat session.
	StartChat(context.Context, *connect.Request[_go.StartChatRequest]) (*connect.Response[_go.StartChatResponse], error)
	// Add a new recipe.
	AddRecipe(context.Context, *connect.Request[_go.AddRecipeRequest]) (*connect.Response[_go.AddRecipeResponse], error)
}

// NewFrontendServiceClient constructs a client for the frontendapi.FrontendService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFrontendServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FrontendServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	frontendServiceMethods := _go.File_frontendapi_frontend_proto.Services().ByName("FrontendService").Methods()
	return &frontendServiceClient{
		getRecipe: connect.NewClient[_go.GetRecipeRequest, _go.GetRecipeResponse](
			httpClient,
			baseURL+FrontendServiceGetRecipeProcedure,
			connect.WithSchema(frontendServiceMethods.ByName("GetRecipe")),
			connect.WithClientOptions(opts...),
		),
		listRecipes: connect.NewClient[_go.ListRecipesRequest, _go.ListRecipesResponse](
			httpClient,
			baseURL+FrontendServiceListRecipesProcedure,
			connect.WithSchema(frontendServiceMethods.ByName("ListRecipes")),
			connect.WithClientOptions(opts...),
		),
		startChat: connect.NewClient[_go.StartChatRequest, _go.StartChatResponse](
			httpClient,
			baseURL+FrontendServiceStartChatProcedure,
			connect.WithSchema(frontendServiceMethods.ByName("StartChat")),
			connect.WithClientOptions(opts...),
		),
		addRecipe: connect.NewClient[_go.AddRecipeRequest, _go.AddRecipeResponse](
			httpClient,
			baseURL+FrontendServiceAddRecipeProcedure,
			connect.WithSchema(frontendServiceMethods.ByName("AddRecipe")),
			connect.WithClientOptions(opts...),
		),
	}
}

// frontendServiceClient implements FrontendServiceClient.
type frontendServiceClient struct {
	getRecipe   *connect.Client[_go.GetRecipeRequest, _go.GetRecipeResponse]
	listRecipes *connect.Client[_go.ListRecipesRequest, _go.ListRecipesResponse]
	startChat   *connect.Client[_go.StartChatRequest, _go.StartChatResponse]
	addRecipe   *connect.Client[_go.AddRecipeRequest, _go.AddRecipeResponse]
}

// GetRecipe calls frontendapi.FrontendService.GetRecipe.
func (c *frontendServiceClient) GetRecipe(ctx context.Context, req *connect.Request[_go.GetRecipeRequest]) (*connect.Response[_go.GetRecipeResponse], error) {
	return c.getRecipe.CallUnary(ctx, req)
}

// ListRecipes calls frontendapi.FrontendService.ListRecipes.
func (c *frontendServiceClient) ListRecipes(ctx context.Context, req *connect.Request[_go.ListRecipesRequest]) (*connect.Response[_go.ListRecipesResponse], error) {
	return c.listRecipes.CallUnary(ctx, req)
}

// StartChat calls frontendapi.FrontendService.StartChat.
func (c *frontendServiceClient) StartChat(ctx context.Context, req *connect.Request[_go.StartChatRequest]) (*connect.Response[_go.StartChatResponse], error) {
	return c.startChat.CallUnary(ctx, req)
}

// AddRecipe calls frontendapi.FrontendService.AddRecipe.
func (c *frontendServiceClient) AddRecipe(ctx context.Context, req *connect.Request[_go.AddRecipeRequest]) (*connect.Response[_go.AddRecipeResponse], error) {
	return c.addRecipe.CallUnary(ctx, req)
}

// FrontendServiceHandler is an implementation of the frontendapi.FrontendService service.
type FrontendServiceHandler interface {
	// Get the recipe for a given recipe ID.
	GetRecipe(context.Context, *connect.Request[_go.GetRecipeRequest]) (*connect.Response[_go.GetRecipeResponse], error)
	// Get the list of recipes.
	ListRecipes(context.Context, *connect.Request[_go.ListRecipesRequest]) (*connect.Response[_go.ListRecipesResponse], error)
	// Start a chat session.
	StartChat(context.Context, *connect.Request[_go.StartChatRequest]) (*connect.Response[_go.StartChatResponse], error)
	// Add a new recipe.
	AddRecipe(context.Context, *connect.Request[_go.AddRecipeRequest]) (*connect.Response[_go.AddRecipeResponse], error)
}

// NewFrontendServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFrontendServiceHandler(svc FrontendServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	frontendServiceMethods := _go.File_frontendapi_frontend_proto.Services().ByName("FrontendService").Methods()
	frontendServiceGetRecipeHandler := connect.NewUnaryHandler(
		FrontendServiceGetRecipeProcedure,
		svc.GetRecipe,
		connect.WithSchema(frontendServiceMethods.ByName("GetRecipe")),
		connect.WithHandlerOptions(opts...),
	)
	frontendServiceListRecipesHandler := connect.NewUnaryHandler(
		FrontendServiceListRecipesProcedure,
		svc.ListRecipes,
		connect.WithSchema(frontendServiceMethods.ByName("ListRecipes")),
		connect.WithHandlerOptions(opts...),
	)
	frontendServiceStartChatHandler := connect.NewUnaryHandler(
		FrontendServiceStartChatProcedure,
		svc.StartChat,
		connect.WithSchema(frontendServiceMethods.ByName("StartChat")),
		connect.WithHandlerOptions(opts...),
	)
	frontendServiceAddRecipeHandler := connect.NewUnaryHandler(
		FrontendServiceAddRecipeProcedure,
		svc.AddRecipe,
		connect.WithSchema(frontendServiceMethods.ByName("AddRecipe")),
		connect.WithHandlerOptions(opts...),
	)
	return "/frontendapi.FrontendService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FrontendServiceGetRecipeProcedure:
			frontendServiceGetRecipeHandler.ServeHTTP(w, r)
		case FrontendServiceListRecipesProcedure:
			frontendServiceListRecipesHandler.ServeHTTP(w, r)
		case FrontendServiceStartChatProcedure:
			frontendServiceStartChatHandler.ServeHTTP(w, r)
		case FrontendServiceAddRecipeProcedure:
			frontendServiceAddRecipeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFrontendServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFrontendServiceHandler struct{}

func (UnimplementedFrontendServiceHandler) GetRecipe(context.Context, *connect.Request[_go.GetRecipeRequest]) (*connect.Response[_go.GetRecipeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("frontendapi.FrontendService.GetRecipe is not implemented"))
}

func (UnimplementedFrontendServiceHandler) ListRecipes(context.Context, *connect.Request[_go.ListRecipesRequest]) (*connect.Response[_go.ListRecipesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("frontendapi.FrontendService.ListRecipes is not implemented"))
}

func (UnimplementedFrontendServiceHandler) StartChat(context.Context, *connect.Request[_go.StartChatRequest]) (*connect.Response[_go.StartChatResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("frontendapi.FrontendService.StartChat is not implemented"))
}

func (UnimplementedFrontendServiceHandler) AddRecipe(context.Context, *connect.Request[_go.AddRecipeRequest]) (*connect.Response[_go.AddRecipeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("frontendapi.FrontendService.AddRecipe is not implemented"))
}
