// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: frontendapi/frontend.proto

package frontendapiconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	_go "github.com/curioswitch/cookchat/frontend/api/go"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ChatServiceName is the fully-qualified name of the ChatService service.
	ChatServiceName = "frontendapi.ChatService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ChatServiceChatProcedure is the fully-qualified name of the ChatService's Chat RPC.
	ChatServiceChatProcedure = "/frontendapi.ChatService/Chat"
)

// ChatServiceClient is a client for the frontendapi.ChatService service.
type ChatServiceClient interface {
	// Chat with a stream of messages.
	Chat(context.Context) *connect.BidiStreamForClient[_go.ChatRequest, _go.ChatResponse]
}

// NewChatServiceClient constructs a client for the frontendapi.ChatService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewChatServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ChatServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	chatServiceMethods := _go.File_frontendapi_frontend_proto.Services().ByName("ChatService").Methods()
	return &chatServiceClient{
		chat: connect.NewClient[_go.ChatRequest, _go.ChatResponse](
			httpClient,
			baseURL+ChatServiceChatProcedure,
			connect.WithSchema(chatServiceMethods.ByName("Chat")),
			connect.WithClientOptions(opts...),
		),
	}
}

// chatServiceClient implements ChatServiceClient.
type chatServiceClient struct {
	chat *connect.Client[_go.ChatRequest, _go.ChatResponse]
}

// Chat calls frontendapi.ChatService.Chat.
func (c *chatServiceClient) Chat(ctx context.Context) *connect.BidiStreamForClient[_go.ChatRequest, _go.ChatResponse] {
	return c.chat.CallBidiStream(ctx)
}

// ChatServiceHandler is an implementation of the frontendapi.ChatService service.
type ChatServiceHandler interface {
	// Chat with a stream of messages.
	Chat(context.Context, *connect.BidiStream[_go.ChatRequest, _go.ChatResponse]) error
}

// NewChatServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewChatServiceHandler(svc ChatServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	chatServiceMethods := _go.File_frontendapi_frontend_proto.Services().ByName("ChatService").Methods()
	chatServiceChatHandler := connect.NewBidiStreamHandler(
		ChatServiceChatProcedure,
		svc.Chat,
		connect.WithSchema(chatServiceMethods.ByName("Chat")),
		connect.WithHandlerOptions(opts...),
	)
	return "/frontendapi.ChatService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ChatServiceChatProcedure:
			chatServiceChatHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedChatServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedChatServiceHandler struct{}

func (UnimplementedChatServiceHandler) Chat(context.Context, *connect.BidiStream[_go.ChatRequest, _go.ChatResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("frontendapi.ChatService.Chat is not implemented"))
}
