// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        (unknown)
// source: frontendapi/frontend.proto

package frontendapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The content of a chat message.
type ChatContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ChatContent_Message
	//	*ChatContent_Audio
	Payload       isChatContent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatContent) Reset() {
	*x = ChatContent{}
	mi := &file_frontendapi_frontend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatContent) ProtoMessage() {}

func (x *ChatContent) ProtoReflect() protoreflect.Message {
	mi := &file_frontendapi_frontend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatContent.ProtoReflect.Descriptor instead.
func (*ChatContent) Descriptor() ([]byte, []int) {
	return file_frontendapi_frontend_proto_rawDescGZIP(), []int{0}
}

func (x *ChatContent) GetPayload() isChatContent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ChatContent) GetMessage() string {
	if x != nil {
		if x, ok := x.Payload.(*ChatContent_Message); ok {
			return x.Message
		}
	}
	return ""
}

func (x *ChatContent) GetAudio() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ChatContent_Audio); ok {
			return x.Audio
		}
	}
	return nil
}

type isChatContent_Payload interface {
	isChatContent_Payload()
}

type ChatContent_Message struct {
	// A text message.
	Message string `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type ChatContent_Audio struct {
	// An audio message.
	Audio []byte `protobuf:"bytes,2,opt,name=audio,proto3,oneof"`
}

func (*ChatContent_Message) isChatContent_Payload() {}

func (*ChatContent_Audio) isChatContent_Payload() {}

// A request to send in a chat.
type ChatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The content of the chat message.
	Content *ChatContent `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	// The recipe to chat about.
	Recipe        string `protobuf:"bytes,2,opt,name=recipe,proto3" json:"recipe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_frontendapi_frontend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontendapi_frontend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_frontendapi_frontend_proto_rawDescGZIP(), []int{1}
}

func (x *ChatRequest) GetContent() *ChatContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ChatRequest) GetRecipe() string {
	if x != nil {
		return x.Recipe
	}
	return ""
}

// A response in a chat.
type ChatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The content of the chat message.
	Content       *ChatContent `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_frontendapi_frontend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontendapi_frontend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_frontendapi_frontend_proto_rawDescGZIP(), []int{2}
}

func (x *ChatResponse) GetContent() *ChatContent {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_frontendapi_frontend_proto protoreflect.FileDescriptor

var file_frontendapi_frontend_proto_rawDesc = string([]byte{
	0x0a, 0x1a, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x72,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x66, 0x72,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x61, 0x70, 0x69, 0x22, 0x4c, 0x0a, 0x0b, 0x43, 0x68, 0x61,
	0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x05, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x05, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x42, 0x09, 0x0a, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x59, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x64, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x63, 0x69, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x63, 0x69,
	0x70, 0x65, 0x22, 0x42, 0x0a, 0x0c, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x61, 0x70,
	0x69, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x32, 0x4e, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x04, 0x43, 0x68, 0x61, 0x74, 0x12, 0x18, 0x2e,
	0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x68, 0x61, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x64, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x75, 0x72, 0x69, 0x6f, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68,
	0x2f, 0x63, 0x6f, 0x6f, 0x6b, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x6f, 0x3b, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x64, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_frontendapi_frontend_proto_rawDescOnce sync.Once
	file_frontendapi_frontend_proto_rawDescData []byte
)

func file_frontendapi_frontend_proto_rawDescGZIP() []byte {
	file_frontendapi_frontend_proto_rawDescOnce.Do(func() {
		file_frontendapi_frontend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_frontendapi_frontend_proto_rawDesc), len(file_frontendapi_frontend_proto_rawDesc)))
	})
	return file_frontendapi_frontend_proto_rawDescData
}

var file_frontendapi_frontend_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_frontendapi_frontend_proto_goTypes = []any{
	(*ChatContent)(nil),  // 0: frontendapi.ChatContent
	(*ChatRequest)(nil),  // 1: frontendapi.ChatRequest
	(*ChatResponse)(nil), // 2: frontendapi.ChatResponse
}
var file_frontendapi_frontend_proto_depIdxs = []int32{
	0, // 0: frontendapi.ChatRequest.content:type_name -> frontendapi.ChatContent
	0, // 1: frontendapi.ChatResponse.content:type_name -> frontendapi.ChatContent
	1, // 2: frontendapi.ChatService.Chat:input_type -> frontendapi.ChatRequest
	2, // 3: frontendapi.ChatService.Chat:output_type -> frontendapi.ChatResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_frontendapi_frontend_proto_init() }
func file_frontendapi_frontend_proto_init() {
	if File_frontendapi_frontend_proto != nil {
		return
	}
	file_frontendapi_frontend_proto_msgTypes[0].OneofWrappers = []any{
		(*ChatContent_Message)(nil),
		(*ChatContent_Audio)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_frontendapi_frontend_proto_rawDesc), len(file_frontendapi_frontend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_frontendapi_frontend_proto_goTypes,
		DependencyIndexes: file_frontendapi_frontend_proto_depIdxs,
		MessageInfos:      file_frontendapi_frontend_proto_msgTypes,
	}.Build()
	File_frontendapi_frontend_proto = out.File
	file_frontendapi_frontend_proto_goTypes = nil
	file_frontendapi_frontend_proto_depIdxs = nil
}
