// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tasksapi/tasks.proto

package tasksapi

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FillPlanRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the plan to fill.
	PlanId        string `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FillPlanRequest) Reset() {
	*x = FillPlanRequest{}
	mi := &file_tasksapi_tasks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FillPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FillPlanRequest) ProtoMessage() {}

func (x *FillPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tasksapi_tasks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FillPlanRequest.ProtoReflect.Descriptor instead.
func (*FillPlanRequest) Descriptor() ([]byte, []int) {
	return file_tasksapi_tasks_proto_rawDescGZIP(), []int{0}
}

func (x *FillPlanRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

type FillPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FillPlanResponse) Reset() {
	*x = FillPlanResponse{}
	mi := &file_tasksapi_tasks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FillPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FillPlanResponse) ProtoMessage() {}

func (x *FillPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tasksapi_tasks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FillPlanResponse.ProtoReflect.Descriptor instead.
func (*FillPlanResponse) Descriptor() ([]byte, []int) {
	return file_tasksapi_tasks_proto_rawDescGZIP(), []int{1}
}

var File_tasksapi_tasks_proto protoreflect.FileDescriptor

const file_tasksapi_tasks_proto_rawDesc = "" +
	"\n" +
	"\x14tasksapi/tasks.proto\x12\btasksapi\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"*\n" +
	"\x0fFillPlanRequest\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\"\x12\n" +
	"\x10FillPlanResponse2Q\n" +
	"\fTasksService\x12A\n" +
	"\bFillPlan\x12\x19.tasksapi.FillPlanRequest\x1a\x1a.tasksapi.FillPlanResponseB7Z5github.com/curioswitch/cookchat/tasks/api/go;tasksapib\x06proto3"

var (
	file_tasksapi_tasks_proto_rawDescOnce sync.Once
	file_tasksapi_tasks_proto_rawDescData []byte
)

func file_tasksapi_tasks_proto_rawDescGZIP() []byte {
	file_tasksapi_tasks_proto_rawDescOnce.Do(func() {
		file_tasksapi_tasks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tasksapi_tasks_proto_rawDesc), len(file_tasksapi_tasks_proto_rawDesc)))
	})
	return file_tasksapi_tasks_proto_rawDescData
}

var file_tasksapi_tasks_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tasksapi_tasks_proto_goTypes = []any{
	(*FillPlanRequest)(nil),  // 0: tasksapi.FillPlanRequest
	(*FillPlanResponse)(nil), // 1: tasksapi.FillPlanResponse
}
var file_tasksapi_tasks_proto_depIdxs = []int32{
	0, // 0: tasksapi.TasksService.FillPlan:input_type -> tasksapi.FillPlanRequest
	1, // 1: tasksapi.TasksService.FillPlan:output_type -> tasksapi.FillPlanResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tasksapi_tasks_proto_init() }
func file_tasksapi_tasks_proto_init() {
	if File_tasksapi_tasks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tasksapi_tasks_proto_rawDesc), len(file_tasksapi_tasks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tasksapi_tasks_proto_goTypes,
		DependencyIndexes: file_tasksapi_tasks_proto_depIdxs,
		MessageInfos:      file_tasksapi_tasks_proto_msgTypes,
	}.Build()
	File_tasksapi_tasks_proto = out.File
	file_tasksapi_tasks_proto_goTypes = nil
	file_tasksapi_tasks_proto_depIdxs = nil
}
