name: Repository Root CI
on:
  push:
    branches:
      - main
    paths:
      - .github/**
      - "*"
  pull_request:
    paths:
      - .github/**
      - "*"
  workflow_dispatch:
  workflow_call:

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: curioswitch/go-build/.github/actions/setup-go@8cee71a440fb70ec08525081efdf8088d2b3618e # v0.8.3

      - run: go run ./build lint
