name: Tasks Server CI
on:
  push:
    branches:
      - main
    paths:
      - common/go/**
      - tasks/server/**
      - tasks/api/go/**
      - .github/workflows/ci-tasks-server.yaml
  pull_request:
    paths:
      - common/go/**
      - tasks/server/**
      - tasks/api/go/**
      - .github/workflows/ci-tasks-server.yaml
  workflow_dispatch:
  workflow_call:

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  ci:
    uses: curioswitch/go-curiostack/.github/workflows/export-go-server-ci.yaml@784dcc35a1f2d90421937ca113bd68e42a446020
    with:
      project_dir: tasks/server
      service: tasks-server
    secrets: inherit
